//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumitQuotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuotationDetail
    {
        public int QuotationDetail_Id { get; set; }
        public int QuotationId { get; set; }
        public int ItemId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsDeleted { get; set; }
        public string ItemName { get; set; }
        public int ItemTypeId { get; set; }
    }
}
