//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumitQuotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Quotation
    {
        public tbl_Quotation()
        {
            this.tbl_QuotationDetail = new HashSet<tbl_QuotationDetail>();
        }
        public int Quotation_Id { get; set; }
        public string QuotationNo { get; set; }
        public DateTime QuotationDate { get; set; }
        public int CustomerId { get; set; }
        public virtual ICollection<tbl_QuotationDetail> tbl_QuotationDetail { get; set; }
    }
}
